baseURL = 'https://w3ird.tech/'
canonifyurls = true
enableRobotsTXT = true
languageCode = 'en-us'
theme = 'etch'
title = 'w3irdrobot blog'

pygmentsCodeFences = true
pygmentsUseClasses = true

[pagination]
pagerSize = 20

[markup.highlight]
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[permalinks]
posts = "/posts/:slug"

[params]
copyright = 'Copyright Â© 2025 w3irdrobot'
dark = 'auto'
description = 'I write and talk about code and probably talk shit about Python at some point as well.'
highlight = true
lnaddress = "w3irdrobot@getalby.com"
siteImage = "images/avatar.png"

[[menu.main]]
identifier = "posts"
name = "posts"
title = "posts"
url = "/"
weight = 10
