[package]
edition = "2024"
name = "solutions"
version = "0.1.0"

[dependencies]
anyhow = "1.0.100"
bdk_wallet = { version = "2.3.0", features = ["all-keys"] }
miniscript = "13.0.0"

[[bin]]
name = "twolocksonegate"
path = "src/twolocksonegate.rs"
